FROM node:22.21.1

WORKDIR /project

# ルート依存関係
COPY package.json package-lock.json ./
COPY tsconfig.json ./
RUN npm install

# backend 依存関係
WORKDIR /project/backend
COPY backend/package*.json ./
COPY backend/tsconfig.json ./
RUN npm install

# ソース
COPY backend/src ./src
COPY backend/prisma ./prisma
RUN npx prisma generate
RUN npx prisma db seed

# shared
WORKDIR /project
COPY shared ./shared

ENV TS_NODE_PROJECT=/project/backend/tsconfig.json

WORKDIR /project/backend

EXPOSE 3000
CMD ["npm", "run", "dev"]
